name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
    - name: Make mvnw executable
      run: chmod +x ./mvnw
    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/easyidentitygenerator-user-generator:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/easyidentitygenerator-user-generator:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/easyidentitygenerator-user-generator:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/easyidentitygenerator-user-generator
